// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeMarket_Klas4_Groep7.Data;

#nullable disable

namespace TreeMarket_Klas4_Groep7.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Claim", b =>
                {
                    b.Property<int>("ClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimID"));

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int");

                    b.HasKey("ClaimID");

                    b.HasIndex("KlantId");

                    b.HasIndex("VeilingId");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Dashboard", b =>
                {
                    b.Property<int>("DashboardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DashboardID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("DashboardID");

                    b.HasIndex("ProductID");

                    b.ToTable("Dashboard");
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GebruikerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GebruikerId");

                    b.ToTable("Gebruiker", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Artikelkenmerken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dagdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("int");

                    b.Property<int>("LeverancierID")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("LeverancierID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Veiling", b =>
                {
                    b.Property<int>("VeilingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeilingID"));

                    b.Property<decimal>("EindPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EindTijd")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HuidigePrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrijsStap")
                        .HasColumnType("int");

                    b.Property<int>("PrijsStrategie")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("StartPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTijd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("VeilingsmeesterID")
                        .HasColumnType("int");

                    b.HasKey("VeilingID");

                    b.HasIndex("ProductID");

                    b.HasIndex("VeilingsmeesterID");

                    b.ToTable("Veiling");
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Klant", b =>
                {
                    b.HasBaseType("TreeMarket_Klas4_Groep7.Models.Gebruiker");

                    b.ToTable("Klant", (string)null);
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Leverancier", b =>
                {
                    b.HasBaseType("TreeMarket_Klas4_Groep7.Models.Gebruiker");

                    b.Property<string>("IBANnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KvKNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bedrijf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Leverancier", (string)null);
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Veilingsmeester", b =>
                {
                    b.HasBaseType("TreeMarket_Klas4_Groep7.Models.Gebruiker");

                    b.Property<DateTime>("PlanDatum")
                        .HasColumnType("datetime2");

                    b.ToTable("Veilingsmeester", (string)null);
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Claim", b =>
                {
                    b.HasOne("TreeMarket_Klas4_Groep7.Models.Klant", "klant")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreeMarket_Klas4_Groep7.Models.Veiling", "Veiling")
                        .WithMany()
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiling");

                    b.Navigation("klant");
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Dashboard", b =>
                {
                    b.HasOne("TreeMarket_Klas4_Groep7.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Product", b =>
                {
                    b.HasOne("TreeMarket_Klas4_Groep7.Models.Leverancier", "Leverancier")
                        .WithMany("Producten")
                        .HasForeignKey("LeverancierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leverancier");
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Veiling", b =>
                {
                    b.HasOne("TreeMarket_Klas4_Groep7.Models.Product", "Product")
                        .WithMany("Veilingen")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreeMarket_Klas4_Groep7.Models.Veilingsmeester", "Veilingsmeester")
                        .WithMany()
                        .HasForeignKey("VeilingsmeesterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Veilingsmeester");
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Klant", b =>
                {
                    b.HasOne("TreeMarket_Klas4_Groep7.Models.Gebruiker", null)
                        .WithOne()
                        .HasForeignKey("TreeMarket_Klas4_Groep7.Models.Klant", "GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Leverancier", b =>
                {
                    b.HasOne("TreeMarket_Klas4_Groep7.Models.Gebruiker", null)
                        .WithOne()
                        .HasForeignKey("TreeMarket_Klas4_Groep7.Models.Leverancier", "GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Veilingsmeester", b =>
                {
                    b.HasOne("TreeMarket_Klas4_Groep7.Models.Gebruiker", null)
                        .WithOne()
                        .HasForeignKey("TreeMarket_Klas4_Groep7.Models.Veilingsmeester", "GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Product", b =>
                {
                    b.Navigation("Veilingen");
                });

            modelBuilder.Entity("TreeMarket_Klas4_Groep7.Models.Leverancier", b =>
                {
                    b.Navigation("Producten");
                });
#pragma warning restore 612, 618
        }
    }
}
